name: stock_prediction
channels:
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - absl-py=0.6.1
  - astor=0.7.1
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.0.2
  - c-ares=1.15.0
  - ca-certificates=2018.03.07
  - certifi=2018.11.29
  - cycler=0.10.0
  - cython=0.29
  - dbus=1.13.2
  - decorator=4.3.0
  - entrypoints=0.2.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gast=0.2.0
  - glib=2.56.2
  - gmp=6.1.2
  - grpcio=1.16.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.8.0
  - hdf5=1.10.2
  - icu=58.2
  - intel-openmp=2019.1
  - ipykernel=5.1.0
  - ipython=7.2.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - jedi=0.13.1
  - jinja2=2.10
  - jpeg=9b
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.3
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - keras=2.2.4
  - keras-applications=1.0.6
  - keras-base=2.2.4
  - keras-preprocessing=1.0.5
  - kiwisolver=1.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc=7.2.0
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.35
  - libprotobuf=3.6.1
  - libsodium=1.0.16
  - libstdcxx-ng=8.2.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.8
  - markdown=3.0.1
  - markupsafe=1.1.0
  - matplotlib=2.2.2
  - mistune=0.8.4
  - mkl=2018.0.3
  - mkl_fft=1.0.6
  - mkl_random=1.0.1
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - ncurses=6.1
  - nltk=3.3.0
  - notebook=5.7.2
  - numpy=1.15.4
  - numpy-base=1.15.4
  - openssl=1.1.1a
  - pandas=0.23.4
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.3.1
  - patsy=0.5.1
  - pcre=8.42
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pip=18.1
  - prometheus_client=0.4.2
  - prompt_toolkit=2.0.7
  - protobuf=3.6.1
  - ptyprocess=0.6.0
  - py4j=0.10.7
  - pygments=2.2.0
  - pyparsing=2.3.0
  - pyqt=5.6.0
  - pyspark=2.4.0
  - python=3.6.7
  - python-dateutil=2.7.5
  - pytz=2018.7
  - pyyaml=3.13
  - pyzmq=17.1.2
  - qt=5.6.3
  - qtconsole=4.4.2
  - readline=7.0
  - scikit-learn=0.20.1
  - scipy=1.1.0
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setuptools=40.6.2
  - sip=4.19.8
  - six=1.11.0
  - sqlite=3.25.3
  - statsmodels=0.9.0
  - tensorboard=1.12.0
  - tensorflow=1.12.0
  - tensorflow-base=1.12.0
  - termcolor=1.1.0
  - terminado=0.8.1
  - testpath=0.4.2
  - tk=8.6.8
  - tornado=5.1.1
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.14.1
  - wheel=0.32.3
  - widgetsnbextension=3.4.2
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.2.5
  - zlib=1.2.11